#!/bin/bash
docker compose down
BRANCH=$(date +%s)
git checkout -b $BRANCH
git add . && git commit -m "${BRANCH}" && git push

cd ./config
git checkout -b $BRANCH
git add . && git commit -m "${BRANCH}" && git push

cd ..
docker compose up -d
