name: links_dashboard-prod
services:
  homers:
    container_name: homer_linkss
    environment:
      APP_GROUP: Content
      APP_LOGO: https://raw.githublinkscontent.com/bastienwirtz/homer/main/public/logo.png
      INIT_ASSETS: "1"
      VIRTUAL_HOST: links.pknw1.co.uk
      VIRTUAL_PORT: "8080"
    image: b4bz/homer
    networks:
      proxy: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config/config.yml
        target: /www/assets/config.yml
        bind:
          create_host_path: true
      - type: bind
        source: ./config/services.yml
        target: /www/assets/services.yml
        bind:
          create_host_path: true
networks:
  proxy:
    name: proxy
    external: true
